### ISSUE TITLE
[Feature Request] Map header value to username

### ISSUE THREAD

**Issue by KairuByte** [BeryJu/hass-auth-header#104]
I've been testing Header Auth with Cloudflare Zero Trust, but I've run into an odd limitation. I have no way of setting what the header passes to Home Assistant. The only value that seems to be passed is the users email address.

Would it be possible to add a list of [email] => [username] translations, to account for such situations?

I'm thinking something along these lines:
```
auth_header:
  username_header: Cf-Access-Authenticated-User-Email
  username_mapping:
    - first.last@host.com: user1
    - second.user@gmail.com: user2
    - second.again@hotmail.com: user2
```
