### ISSUE TITLE
I can no longer log in to HASS using my reverse proxy AFTER deleting hass-auth-header 

### ISSUE THREAD

**Issue by Gecko-with-a-hat** [BeryJu/hass-auth-header#334]
I was playing around with this software so that I could use my authentik credentials to log into hass. had it setup and working with npm and authentik. Decided to not keep using it in the end. So I removed the repository from HACS and deleted the corresponding config lines. But now I can no longer log into hass through my reverse proxy. I get a ton of errors in the logs, 

running hassOS on a VM. Latest version. config.yaml:
```

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Reverse proxy and SSO settings
http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 10.0.0.0/8
```

The errors I get in the log are:
`homeassistant.auth.InvalidProvider: Auth provider auth_header, None not available`
and
`ERROR (MainThread) [aiohttp.server] Error handling request`

Not really sure what more I need to do to revert back to default login setup.
